name: Non-Production Deployment - Private Endpoint

on:
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Subscription'
        required: true
        type: choice
        options:
          - dbse-n-1
          - dbsm-n-1
      resource_group:
        description: 'Resource Group'
        required: true
        type: string
      vnet_name:
        description: 'VNet Name'
        required: true
        type: choice
        options:
          - dbse-n-vnet1
          - dbse-n-vnet2
          - dbse-n-vnet3
          - dbsm-n-vnet1
          - dbsm-n-vnet2
          - dbsm-n-vnet3
      subnet_name:
        description: 'Subnet Name'
        required: true
        type: string
      resource_type:
        description: 'Resource Type'
        required: true
        type: choice
        options:
          - Storage Account
          - Cosmos DB
          - Key Vault
          - SQL
          - Data Factory
          - Search Service
      subresource_name:
        description: 'Sub Resource Name'
        required: true
        type: choice
        options: [blob, Vault, sql, file, table, queue, mongodb, search, factory]
      resource_name:
        description: 'Resource Name'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ssppaps1arpscr1.azurecr.io/ubuntu2204-build-agent:latest
      credentials:
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up service principal
      run: |
        echo "Using non-production service principals"
        echo "ARM_CLIENT_ID=${{ secrets.SP_AZURE_DNAE_NPROD_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.SP_AZURE_DNAE_NPROD_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ github.event.inputs.subscription_id }}" >> $GITHUB_ENV

    - name: Create branch
      run: |
        git checkout -b "pe-deployment-${{ github.event.inputs.resource_name }}"

    - name: Generate JSON configuration
      run: |
        ./scripts/private_endpoint/generate-config.ps1 `
          -subscriptionName ${{ inputs.subscription }} `
          -resourceGroupName ${{ inputs.resource_group }} `
          -vnetName ${{ inputs.vnet_name }} `
          -subnetName ${{ inputs.subnet_name }} `
          -resourceType ${{ inputs.resource_type }} `
          -subResourceName ${{ inputs.subresource_name }} `
          -resourceName ${{ inputs.resource_name }}

    - name: Verification
      run: |
        ./scripts/private_endpoint/verification.ps1 `
          -subscriptionName ${{ inputs.subscription }} `
          -resourceGroupName ${{ inputs.resource_group }} `
          -vnetName ${{ inputs.vnet_name }} `          
          -subnetName ${{ inputs.subnet_name }} `
          -resourceType ${{ inputs.resource_type }} `
          -subResourceName ${{ inputs.subresource_name }} `
          -resourceName ${{ inputs.resource_name }}

    - name: Call Pipeline Template - Plan
      uses: ./.github/workflows/pipeline-template.yml
      with:
        environment: non-production
        subscription: ${{ inputs.subscription }}
        resource_group: ${{ inputs.resource_group }}
        resource_type: private_endpoint
        resource_name: ${{ inputs.resource_name }}

    - name: Create PR for Approval
      if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'approved'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Apply private endpoint deployment'
        title: 'Apply private endpoint deployment for ${{ inputs.resource_name }}'
        body: 'This PR applies the private endpoint deployment after approval'

    - name: Call Pipeline Template - Apply
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == 'true'
      uses: ./.github/workflows/pipeline-template.yml
      with:
        environment: non-production
        subscription: ${{ inputs.subscription }}
        resource_group: ${{ inputs.resource_group }}
        resource_type: private_endpoint
        resource_name: ${{ inputs.resource_name }}

    - name: Cleanup
      run: |
        git remote set-url origin https://github.com/${{ github.repository }}.git
